name: Test 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Primeiro comando
        run: echo Cheguei galera!

      - name: Segundo comando
        run: |
          ls -la
          pwd
          uptime
          df -h
          
